apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-pass
type: Opaque
data:
  # Default password is "admin".
  password: YWRtaW4=
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/mySql/secret.yaml
