apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/mySql/service.yaml
